=== Spanarchie/tet-apis/services/touchpoints/schema/tp_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "touchpoint": {
      "type": "string"
    },
    "conversion_rate": {
      "type": "number"
    },
    "campaign_cost": {
      "type": "integer"
    },
    "sellers cost": {
      "type": "number"
    },
    "sellers_cost_updates": {
      "type": "number"
    }
  },
  "required": [
    "touchpoint",
    "conversion_rate",
    "campaign_cost",
    "sellers cost",
    "sellers_cost_updates"
  ]
}

=== Spanarchie/tet-apis/services/touchpoints/schema/tp_list.json
[
  {
    "touchpoint": "Touchpoint1",
    "conversion_rate": 6.35,
    "campaign_cost": 100,
    "sellers cost": 25.00,
    "sellers_cost_updates": 2.50
  },
  {
    "touchpoint": "Touchpoint2",
    "conversion_rate": 6.35,
    "campaign_cost": 100,
    "sellers cost": 25.00,
    "sellers_cost_updates": 2.50
  },
  {
    "touchpoint": "Touchpoint3",
    "conversion_rate": 6.35,
    "campaign_cost": 100,
    "sellers cost": 25.00,
    "sellers_cost_updates": 2.50
  },
  {
    "touchpoint": "Touchpoint4",
    "conversion_rate": 6.35,
    "campaign_cost": 100,
    "sellers cost": 25.00,
    "sellers_cost_updates": 2.50
  },
  {
    "touchpoint": "Touchpoint5",
    "conversion_rate": 6.35,
    "campaign_cost": 100,
    "sellers cost": 25.00,
    "sellers_cost_updates": 2.50
  },
  {
    "touchpoint": "Touchpoint6",
    "conversion_rate": 6.35,
    "campaign_cost": 100,
    "sellers cost": 25.00,
    "sellers_cost_updates": 2.50
  },
  {
    "touchpoint": "Touchpoint7",
    "conversion_rate": 6.35,
    "campaign_cost": 100,
    "sellers cost": 25.00,
    "sellers_cost_updates": 2.50
  }
]
