=== Spanarchie/tet-apis/services/campaign/schema/cmp_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "campaign": {
      "type": "string"
    },
    "industry": {
      "type": "string"
    },
    "target": {
      "type": "string"
    },
    "touchpoints": {
      "type": "array",
      "items": [
        {
          "type": "string"
        },
        {
          "type": "string"
        },
        {
          "type": "string"
        }
      ]
    },
    "Predicted Goal": {
      "type": "object",
      "properties": {
        "Top": {
          "type": "integer"
        },
        "Ideal": {
          "type": "integer"
        },
        "Low": {
          "type": "integer"
        }
      },
      "required": [
        "Top",
        "Ideal",
        "Low"
      ]
    },
    "Campaign Totals": {
      "type": "object",
      "properties": {
        "Actual Goal": {
          "type": "string"
        },
        "Conversion Rate": {
          "type": "number"
        },
        "Starting Budget": {
          "type": "number"
        },
        "Cost": {
          "type": "number"
        },
        "Improvements Cost": {
          "type": "integer"
        },
        "Success Fee": {
          "type": "number"
        },
        "Budget Rollover": {
          "type": "number"
        }
      },
      "required": [
        "Actual Goal",
        "Conversion Rate",
        "Starting Budget",
        "Cost",
        "Improvements Cost",
        "Success Fee",
        "Budget Rollover"
      ]
    }
  },
  "required": [
    "campaign",
    "industry",
    "target",
    "touchpoints",
    "Predicted Goal",
    "Campaign Totals"
  ]
}

=== Spanarchie/tet-apis/services/campaign/schema/cmp_list.json
[
  {
    "campaign": "Campaign1",
    "industry": "xxx",
    "target": "BrandAwareness",
    "touchpoints": [
      "Touchpoint1",
      "Touchpoint2",
      "Touchpoint5"
    ],
    "Predicted Goal": {
      "Top": 999,
      "Ideal": 777,
      "Low": 555
    },
    "Campaign Totals": {
      "Actual Goal": "785",
      "Conversion Rate": 55.55,
      "Starting Budget": 500.50,
      "Cost": 275.45,
      "Improvements Cost": 150,
      "Success Fee": 75.50,
      "Budget Rollover": 2.50
    }
  },
  {
    "campaign": "Campaign2",
    "industry": "xxx",
    "target": "BrandAwareness",
    "touchpoints": [
      "Touchpoint1",
      "Touchpoint2",
      "Touchpoint5"
    ],
    "Predicted Goal": {
      "Top": 999,
      "Ideal": 777,
      "Low": 555
    },
    "Campaign Totals": {
      "Actual Goal": "785",
      "Conversion Rate": 55.55,
      "Starting Budget": 500.50,
      "Cost": 275.45,
      "Improvements Cost": 150,
      "Success Fee": 75.50,
      "Budget Rollover": 2.50
    }
  },
  {
    "campaign": "Campaign3",
    "industry": "xxx",
    "target": "BrandAwareness",
    "touchpoints": [
      "Touchpoint1",
      "Touchpoint2",
      "Touchpoint5"
    ],
    "Predicted Goal": {
      "Top": 999,
      "Ideal": 777,
      "Low": 555
    },
    "Campaign Totals": {
      "Actual Goal": "785",
      "Conversion Rate": 55.55,
      "Starting Budget": 500.50,
      "Cost": 275.45,
      "Improvements Cost": 150,
      "Success Fee": 75.50,
      "Budget Rollover": 2.50
    }
  },
  {
    "campaign": "Campaign4",
    "industry": "xxx",
    "target": "BrandAwareness",
    "touchpoints": [
      "Touchpoint1",
      "Touchpoint2",
      "Touchpoint5"
    ],
    "Predicted Goal": {
      "Top": 999,
      "Ideal": 777,
      "Low": 555
    },
    "Campaign Totals": {
      "Actual Goal": "785",
      "Conversion Rate": 55.55,
      "Starting Budget": 500.50,
      "Cost": 275.45,
      "Improvements Cost": 150,
      "Success Fee": 75.50,
      "Budget Rollover": 2.50
    }
  },
  {
    "campaign": "Campaign5",
    "industry": "xxx",
    "target": "BrandAwareness",
    "touchpoints": [
      "Touchpoint1",
      "Touchpoint2",
      "Touchpoint5"
    ],
    "Predicted Goal": {
      "Top": 999,
      "Ideal": 777,
      "Low": 555
    },
    "Campaign Totals": {
      "Actual Goal": "785",
      "Conversion Rate": 55.55,
      "Starting Budget": 500.50,
      "Cost": 275.45,
      "Improvements Cost": 150,
      "Success Fee": 75.50,
      "Budget Rollover": 2.50
    }
  },
  {
    "campaign": "Campaign6",
    "industry": "xxx",
    "target": "BrandAwareness",
    "touchpoints": [
      "Touchpoint1",
      "Touchpoint2",
      "Touchpoint5"
    ],
    "Predicted Goal": {
      "Top": 999,
      "Ideal": 777,
      "Low": 555
    },
    "Campaign Totals": {
      "Actual Goal": "785",
      "Conversion Rate": 55.55,
      "Starting Budget": 500.50,
      "Cost": 275.45,
      "Improvements Cost": 150,
      "Success Fee": 75.50,
      "Budget Rollover": 2.50
    }
  },
  {
    "campaign": "Campaign7",
    "industry": "xxx",
    "target": "BrandAwareness",
    "touchpoints": [
      "Touchpoint1",
      "Touchpoint2",
      "Touchpoint5"
    ],
    "Predicted Goal": {
      "Top": 999,
      "Ideal": 777,
      "Low": 555
    },
    "Campaign Totals": {
      "Actual Goal": "785",
      "Conversion Rate": 55.55,
      "Starting Budget": 500.50,
      "Cost": 275.45,
      "Improvements Cost": 150,
      "Success Fee": 75.50,
      "Budget Rollover": 2.50
    }
  },
  {
    "campaign": "Campaign8",
    "industry": "xxx",
    "target": "BrandAwareness",
    "touchpoints": [
      "Touchpoint1",
      "Touchpoint2",
      "Touchpoint5"
    ],
    "Predicted Goal": {
      "Top": 999,
      "Ideal": 777,
      "Low": 555
    },
    "Campaign Totals": {
      "Actual Goal": "785",
      "Conversion Rate": 55.55,
      "Starting Budget": 500.50,
      "Cost": 275.45,
      "Improvements Cost": 150,
      "Success Fee": 75.50,
      "Budget Rollover": 2.50
    }
  }
]
